### ISSUE TITLE
[ddos.json] Unable to resolve #{octet} directive

### ISSUE THREAD

**Issue by rmoff** [ShadowTraffic/shadowtraffic-examples#1]
Using https://github.com/ShadowTraffic/shadowtraffic-examples/blob/master/ddos.json verbatim except for the Kafka broker, I get this error when launching ShadowTraffic: 

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve #{octet} directive.
       at com.github.javafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:360)
       at com.github.javafaker.service.FakeValuesService.expression(FakeValuesService.java:322)
       at com.github.javafaker.Faker.expression(Faker.java:653)
       at io.shadowtraffic.generator.compiler$fn__2523$f__2524.invoke(compiler.cljc:77)
       at io.shadowtraffic.generator.types.GeneratorCall.execute(types.cljc:9)
       at io.shadowtraffic.generator.compiler$evaluate.invokeStatic(compiler.cljc:35)
       at io.shadowtraffic.generator.compiler$evaluate.invoke(compiler.cljc:25)
       at io.shadowtraffic.generator.compiler$evaluate$fn__2512.invoke(compiler.cljc:42)
       at clojure.walk$prewalk.invokeStatic(walk.clj:65)
[…]
```

**Comment by rmoff** [comment]
```
❯ docker images|grep shadow
shadowtraffic/shadowtraffic                      latest                        589b094c41ac   4 months ago    570MB
```

I'm guessing `latest` isn't actually the latest :)

**Comment by rmoff** [comment]
```
❯ docker images|grep shadow
shadowtraffic/shadowtraffic                      latest                        65fb65530457   2 days ago      587MB
shadowtraffic/shadowtraffic                      <none>                        589b094c41ac   4 months ago    570MB
```

Works fine now!

**Comment by MichaelDrogalis** [comment]
Aha, glad it wasn't a bug. :)
